export const COPY = {
  ru: {
    skip: "К содержанию",
    logoAria: "DUMMFOUND — на главную",
    navAria: "Основная навигация",
    langGroup: "Язык",
    menu: "Меню",
    drawerBackdrop: "Закрыть меню",
    radioOpen: "Radio",
    radioTitle: "Radio",
    radioClose: "Закрыть радио",
    radioPlay: "Воспроизвести",
    radioPause: "Стоп",
    radioVolume: "Громкость",
    nav: {
      about: "О проекте",
      music: "Музыка",
      booking: "Букинг",
      contact: "Контакты",
      gigs: "Выступления",
      app: "DUMMFOUND OS",
    },
    heroIntro: "Вступление",
    heroCtaMusic: "Music",
    heroCtaBooking: "Booking",
    heroPromoLabel: "Enhanced",
    heroPromoTitle: "Lørean & DUMMFOUND — Together",
    heroPromoDate: "11.09.26",
    heroPromoCta: "Предзаказ",
    heroPromoClose: "Скрыть",
    tourIntroTitle: "Братания Тур",
    tourIntroClose: "Закрыть",
    tourIntroWait: "Закрыть через {n}",
    aboutLabel: "О проекте",
    aboutP:
      "Артист современной андеграунд-сцены, с релизами на барселонском Lone Romantic, московских СТВОЛ & System 108. Актуальная электронная музыка, экзистенциально вдохновленная жизнью и особенной атмосферой полумиллионного индустриального города в центре России.",
    musicLabel: "Музыка",
    gigsLabel: "Выступления",
    releases: [
      {
        title: "EP — Tour De Dance",
        meta: "System 108 · 2026",
        href: "https://music.yandex.ru/album/41307841",
        linkLabel: "слушать",
      },
      {
        title: "EP — Industrialnaya Street",
        meta: "СТВОЛ · 2024",
        href: "https://music.yandex.ru/album/33035332",
        linkLabel: "слушать",
      },
      {
        title: "БРАТАНИЯ",
        meta: "System 108 · 2025",
        href: "https://music.yandex.ru/album/37284963/track/140713088?utm_source=web&utm_medium=copy_link",
        linkLabel: "слушать",
      },
      {
        title:
          "Подкаст №349 — супер премиум сет DUMMFOUND с SUPER PREMIUM DJ & FRIENDS",
        meta: "System 108 · 2026",
        href: "https://soundcloud.com/system108/system108podcast349?si=05bda392fdea4683b803d93e37861ea7&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "слушать",
      },
      {
        title:
          "Judder w/ DUMMFOUND @ KURS Radio 21.09.25",
        meta: "JUDDER · 2025",
        href: "https://soundcloud.com/kurs_radio/judder-w-dummfound-kurs-radio-210925?si=1b28fa06e17f47f49271699963485e06&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "слушать",
      },
      {
        title:
          "STVOL.TV: РЕЙВ ЛЕГЕНДЫ",
        meta: "STVOL.TV · 2024",
        href: "https://soundcloud.com/stvolrecords/stvol12-audio_dummfound?si=0838798ab2014aa193407b33e71af351&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "слушать",
      },
      {
        title: "SoundCloud",
        meta: "архив сетов и демо",
        href: "https://soundcloud.com/dummfound",
        linkLabel: "перейти",
      },
    ],
    gigs: [
      {
        slug: "ekaterinburg-161026",
        title: "Екатеринбург",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "16.10.2026",
        location: "Екатеринбург, Россия",
        linkLabel: "подробнее",
        body: "Выступление в Екатеринбурге.",
      },
      {
        slug: "chelyabinsk-171026",
        title: "Челябинск",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "17.10.2026",
        location: "Челябинск, Россия",
        linkLabel: "подробнее",
        body: "Выступление в Челябинске.",
      },
      {
        slug: "krasnoyarsk-241026",
        title: "Красноярск",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "24.10.2026",
        location: "Красноярск, Россия",
        linkLabel: "подробнее",
        body: "Выступление в Красноярске.",
      },
      {
        slug: "vladivostok-011126",
        title: "Владивосток",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "01.11.2026",
        location: "Владивосток, Россия",
        linkLabel: "подробнее",
        body: "Выступление во Владивостоке.",
      },
      {
        slug: "voronezh-071126",
        title: "Воронеж",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "07.11.2026",
        location: "Воронеж, Россия",
        linkLabel: "подробнее",
        body: "Выступление в Воронеже.",
      },
      {
        slug: "moscow-tba",
        title: "Москва",
        type: "Братания Тур",
        typeNote: "совместно с WASTA",
        date: "TBA",
        location: "Москва, Россия",
        linkLabel: "подробнее",
        body: "Выступление в Москве. Дата уточняется.",
      },
    ],
    gigsBackLabel: "К выступлениям",
    gigsTicketsLabel: "Билеты",
    gigsNotFound: "Событие не найдено.",
    gigsHint: "Нажмите на дату, чтобы узнать подробности.",
    gigsDetailsSoon: "Подробности скоро.",
    bookingLabel: "Букинг",
    bookingP:
      "Запросы на клубы, фестивали, подкасты и коллаборации — через e-mail. Техрайдер и пресс-кит высылаются по запросу.",
    bookingCta: "Забронировать",
    formatLabel: "Форматы",
    formatVal: "dj set",
    geoLabel: "География",
    geoVal: "EU / СНГ — обсуждается индивидуально",
    contactLabel: "Контакты",
    contactFormIntro:
      "Отправьте сообщение прямо с сайта — ответ придёт на указанную почту.",
    contactFormName: "Имя",
    contactFormEmail: "Электронная почта",
    contactFormMessage: "Сообщение",
    contactFormSubmit: "Отправить",
    contactFormSending: "Отправка…",
    contactFormSuccess: "Сообщение отправлено. Скоро ответим.",
    contactFormError:
      "Не удалось отправить. Попробуйте ещё раз или напишите на почту выше.",
    contactFormHelper:
      "Чтобы отправить сообщение, заполните email и текст сообщения.",
    contactFormValidationSummary:
      "Исправьте поля выше: укажите корректный email и текст сообщения.",
    contactFormErrorEmailRequired: "Укажите email.",
    contactFormErrorEmailInvalid: "Проверьте формат email.",
    contactFormErrorMessageRequired: "Напишите текст сообщения.",
    contactFormToggleOpen: "Написать",
    contactFormToggleClose: "Скрыть",
    instagramSocialLabel: "Instagram",
    footerInstagramDisclaimer:
      "*принадлежит Meta, признанной экстремистской и запрещенной на территории РФ",
  },
  en: {
    skip: "Skip to content",
    logoAria: "DUMMFOUND — home",
    navAria: "Main navigation",
    langGroup: "Language",
    menu: "Menu",
    drawerBackdrop: "Close menu",
    radioOpen: "Radio",
    radioTitle: "Radio",
    radioClose: "Close radio",
    radioPlay: "Play",
    radioPause: "Stop",
    radioVolume: "Volume",
    nav: {
      about: "About",
      music: "Music",
      booking: "Booking",
      contact: "Contact",
      gigs: "Gigs",
      app: "DUMMFOUND OS",
    },
    heroIntro: "Introduction",
    heroCtaMusic: "Music",
    heroCtaBooking: "Booking",
    heroPromoLabel: "Enhanced",
    heroPromoTitle: "Lørean & DUMMFOUND — Together",
    heroPromoDate: "11.09.26",
    heroPromoCta: "Pre-order",
    heroPromoClose: "Hide",
    tourIntroTitle: "Bratania Tour",
    tourIntroClose: "Close",
    tourIntroWait: "Close in {n}",
    aboutLabel: "About",
    aboutP:
      "Underground electronic artist with releases on Barcelona’s Lone Romantic and Moscow labels СТВОЛ & System 108. Contemporary dance music shaped by life and the atmosphere of a half‑million industrial city in central Russia.",
    musicLabel: "Music",
    gigsLabel: "Gigs",
    releases: [
      {
        title: "EP — Tour De Dance",
        meta: "System 108 · 2026",
        href: "https://music.yandex.ru/album/41307841",
        linkLabel: "listen",
      },
      {
        title: "EP — Industrialnaya Street",
        meta: "СТВОЛ · 2024",
        href: "https://music.yandex.ru/album/33035332",
        linkLabel: "listen",
      },
      {
        title:
          "BRATANIA",
        meta: "System 108 · 2025",
        href: "https://music.yandex.ru/album/37284963/track/140713088?utm_source=web&utm_medium=copy_link",
        linkLabel: "listen",
      },
      {
        title:
          "Podcast #349 — DUMMFOUND super premium set with SUPER PREMIUM DJ & FRIENDS",
        meta: "System 108 · 2026",
        href: "https://soundcloud.com/system108/system108podcast349?si=05bda392fdea4683b803d93e37861ea7&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "listen",
      },   {
        title:
          "Judder w/ DUMMFOUND @ KURS Radio 21.09.25",
        meta: "JUDDER · 2025",
        href: "https://soundcloud.com/kurs_radio/judder-w-dummfound-kurs-radio-210925?si=1b28fa06e17f47f49271699963485e06&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "listen",
      },
      {
        title:
          "STVOL.TV: LEGEND RAVE",
        meta: "STVOL.TV · 2024",
        href: "https://soundcloud.com/stvolrecords/stvol12-audio_dummfound?si=0838798ab2014aa193407b33e71af351&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
        linkLabel: "listen",
      },
      {
        title: "SoundCloud",
        meta: "sets & demo archive",
        href: "https://soundcloud.com/dummfound",
        linkLabel: "open",
      },
    ],
    gigs: [
      {
        slug: "ekaterinburg-161026",
        title: "Yekaterinburg",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "16.10.2026",
        location: "Yekaterinburg, Russia",
        linkLabel: "details",
        body: "Live in Yekaterinburg.",
      },
      {
        slug: "chelyabinsk-171026",
        title: "Chelyabinsk",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "17.10.2026",
        location: "Chelyabinsk, Russia",
        linkLabel: "details",
        body: "Live in Chelyabinsk.",
      },
      {
        slug: "krasnoyarsk-241026",
        title: "Krasnoyarsk",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "24.10.2026",
        location: "Krasnoyarsk, Russia",
        linkLabel: "details",
        body: "Live in Krasnoyarsk.",
      },
      {
        slug: "vladivostok-011126",
        title: "Vladivostok",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "01.11.2026",
        location: "Vladivostok, Russia",
        linkLabel: "details",
        body: "Live in Vladivostok.",
      },
      {
        slug: "voronezh-071126",
        title: "Voronezh",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "07.11.2026",
        location: "Voronezh, Russia",
        linkLabel: "details",
        body: "Live in Voronezh.",
      },
      {
        slug: "moscow-tba",
        title: "Moscow",
        type: "Bratania Tour",
        typeNote: "with WASTA",
        date: "TBA",
        location: "Moscow, Russia",
        linkLabel: "details",
        body: "Live in Moscow. Date TBA.",
      },
    ],
    gigsBackLabel: "Back to gigs",
    gigsTicketsLabel: "Tickets",
    gigsNotFound: "Event not found.",
    gigsHint: "Tap a date for details.",
    gigsDetailsSoon: "Details coming soon.",
    bookingLabel: "Booking",
    bookingP:
      "For clubs, festivals, podcasts and collaborations — email. Tech rider and press kit on request.",
    bookingCta: "Booking",
    formatLabel: "Formats",
    formatVal: "dj set",
    geoLabel: "Territory",
    geoVal: "EU / CIS — discussed individually",
    contactLabel: "Contact",
    contactFormIntro:
      "Send a message from the site — we’ll reply to the email you enter.",
    contactFormName: "Name",
    contactFormEmail: "Email",
    contactFormMessage: "Message",
    contactFormSubmit: "Send",
    contactFormSending: "Sending…",
    contactFormSuccess: "Message sent. We’ll get back to you soon.",
    contactFormError:
      "Couldn’t send. Try again or use the email address above.",
    contactFormHelper:
      "To send a message, fill in your email and message text.",
    contactFormValidationSummary:
      "Fix the fields above — enter a valid email and your message.",
    contactFormErrorEmailRequired: "Enter your email.",
    contactFormErrorEmailInvalid: "Check the email format.",
    contactFormErrorMessageRequired: "Enter your message.",
    contactFormToggleOpen: "Write",
    contactFormToggleClose: "Hide",
    instagramSocialLabel: "Instagram",
    footerInstagramDisclaimer:
      "*принадлежит Meta, признанной экстремистской и запрещенной на территории РФ",
  },
};
